### ISSUE TITLE
ValueError: Price for ARS has not yet been derived

### ISSUE THREAD

**Issue by wmbutler** [xeroc/bitshares-pricefeed#11]
BitcoinAverage We encountered an error loading live data. Trying to recover from cache! (
Error fetching results from BitcoinAverage! (key: expected bytes or bytearray, but got 'NoneType'))

Google We encountered an error loading live data. Trying to recover from cache! (
Error fetching results from Google! (could not convert string to float: 'c){var d=Ya;return Object.prototype.hasOwnProperty.call(d'))
'backing_symbol' not in self.price[alias]
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/bitshares-pricefeed", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/bitshares_pricefeed/ui.py", line 18, in new_func
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/uptick/decorators.py", line 50, in new_func
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/uptick/decorators.py", line 77, in new_func
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/uptick/decorators.py", line 98, in new_func
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/bitshares_pricefeed/cli.py", line 88, in update
    feed.derive(assets)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/bitshares_pricefeed/pricefeed.py", line 400, in derive
    self.obtain_price_change(symbol)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/bitshares_pricefeed/pricefeed.py", line 66, in obtain_price_change
    raise ValueError("Price for %s has not yet been derived" % symbol)
ValueError: Price for ARS has not yet been derived

**Comment by wmbutler** [comment]
Commenting ARS resolved this
