### ISSUE TITLE
HERTZ Algorithm Based Asset price feed script request

### ISSUE THREAD

**Issue by grctest** [xeroc/bitshares-pricefeed#3]
Hey,

I've created a new algorithm based asset (FBA/MPA) called HERTZ which oscillates the price feed using a sin wave: https://bitsharestalk.org/index.php/topic,24161.msg306505.html

I'd appreciate support in your price feeds, so that more witnesses will be able to provide feeds.

https://openledger.io/asset/HERTZ/
http://cryptofresh.com/a/HERTZ

---

**Replicated post from above thread:**

Existing haskell price feed script: https://github.com/grctest/HERTZ-Price-feed-script/

Reference hero file: https://github.com/xeroc/bitshares-pricefeed/blob/master/bitshares_pricefeed/examples/hero.yaml

hero formula (line 41):
`formula: 1.05 ** ((date.today() - date(1913, 12, 23)).days / 365.2425) / {quoteSettlement_price}`

The haskell script could be replicated in python, or we could use the haskell script to precompute a large CSV of blocknumbers to modify the latest price feed value with.
`formula: quoteSettlement_price + read_CSV_For_Wave_Value(BlockNumber)`

The python price feed script uses time/dates instead of block numbers, so perhaps there will be a difference in computed values between haskell and python.

python implementation? (I don't know python)

```
import math
import date

quoteSettlement_price = XDR
Time_In_Period = one month duration
amplitude = 0.5

x_value = remainder of (((date.today() - date(Asset_Genesis_Date_Timestamp))/Time_In_Period)/1.00))  // to return 0.xx

feed_price = quoteSettlement_price + (((quoteSettlement_price * amplitude)*(sin((x_value * Time_In_Period)) * ((2*math.pi)/Time_In_Period) ))))
```

**Comment by grctest** [comment]
Update: https://steemit.com/beyondbitcoin/@cm-steem/hertz-haskell-price-feed-script-update

I've created a simplified haskell script as a reference: https://github.com/grctest/HERTZ-Price-feed-script/blob/master/min_hertz.hs

**Comment by grctest** [comment]
Hey @xeroc, I know you're a busy guy but I'd massively appreciate some input on the HERTZ idea, thanks 👍

**Comment by grctest** [comment]
I've created an [initial hertz.yaml configuration](https://github.com/BTS-CM/bitshares-pricefeed/blob/master/bitshares_pricefeed/examples/hertz.yaml), but I have no idea how to use this script to produce the price feed..

I changed hertz.yaml to default.yaml so that 'python3 cli.py create' creates the config.yml from my hertz script.

When I go to run 'python3 cli.py update' I get:
```
python3 cli.py update
Traceback (most recent call last):
  File "cli.py", line 5, in <module>
    cli.main()
  File "/home/username/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/username/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/username/.local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/username/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/username/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/username/.local/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/username/.local/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/username/bitshares-pricefeed/bitshares_pricefeed/ui.py", line 16, in new_func
    ctx.config = yaml.load(open(ctx.obj["configfile"]))
  File "/home/username/.local/lib/python3.5/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/home/username/.local/lib/python3.5/site-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/home/username/.local/lib/python3.5/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/username/.local/lib/python3.5/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/username/.local/lib/python3.5/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/username/.local/lib/python3.5/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/username/.local/lib/python3.5/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/username/.local/lib/python3.5/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/username/.local/lib/python3.5/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/username/.local/lib/python3.5/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/home/username/.local/lib/python3.5/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/username/.local/lib/python3.5/site-packages/yaml/parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block mapping
  in "config.yml", line 10, column 9
expected <block end>, but found '<scalar>'
  in "config.yml", line 44, column 42
```

I tried just using pricefeed.py but to no luck:
```
cm@ubuntu:~/bitshares-pricefeed/bitshares_pricefeed$ python3 pricefeed.py hertz
Traceback (most recent call last):
  File "pricefeed.py", line 10, in <module>
    from . import sources
SystemError: Parent module '' not loaded, cannot perform relative import
cm@ubuntu:~/bitshares-pricefeed/bitshares_pricefeed$ python3 pricefeed.py HERTZ
Traceback (most recent call last):
  File "pricefeed.py", line 10, in <module>
    from . import sources
SystemError: Parent module '' not loaded, cannot perform relative import
```

I did try changing hero.yaml to default.yaml, and running python3 cly.py update did work, which makes me think there's something wrong specifically with my hertz.yaml file.. could it be the use of math.pi, math.sin and time.time within the formula?

Cheers.

**Comment by grctest** [comment]
I'm pretty sure it's complaining solely about the yaml formatting of the following:

```
formula: {quoteSettlement_price} + (({quoteSettlement_price} * 0.5) * math.sin(((((time.time() - 1444745544) / 2629746 ) % 1) * 2629746) * ((2 * math.pi ) / 2629746)))
```

I imported math.sin, math.pi and time into both the cli.py and pricefeed.py scripts, but it didn't change anything. If I reduce the formula to simply the quotesettlement_price it works.
