### ISSUE TITLE
Hertz.yaml & Hero.yaml - assert "price" not in args[0], "You cannot provide a 'price' this way"

### ISSUE THREAD

**Issue by bangzi1001** [xeroc/bitshares-pricefeed#38]
The error below occurred when using hertz.yaml & hero.yaml:

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/bitshares-pricefeed", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/bitshares_pricefeed/ui.py", line 20, in new_func
    return ctx.invoke(f, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/uptick/decorators.py", line 45, in new_func
    return ctx.invoke(f, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/uptick/decorators.py", line 102, in new_func
    return ctx.invoke(f, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/uptick/decorators.py", line 127, in new_func
    return ctx.invoke(f, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/bitshares_pricefeed/cli.py", line 199, in update
    quote=price["short_backing_symbol"])
  File "/home/ubuntu/.local/lib/python3.5/site-packages/bitshares/price.py", line 89, in __init__
    assert "price" not in args[0], "You cannot provide a 'price' this way"
AssertionError: You cannot provide a 'price' this way

**Comment by Zapata** [comment]
Could you test with [my version](https://github.com/Zapata/bitshares-pricefeed)?
I can publish correctly after some fixes.
