### ISSUE TITLE
Launch Error

### ISSUE THREAD

**Issue by wmbutler** [xeroc/bitshares-pricefeed#8]
OS: Ubuntu xenial
Python: 

```
ubuntu@ip-172-31-51-77:~$ python3 --version
Python 3.5.2
```

```
ubuntu@ip-172-31-51-77:~$ bitshares-pricefeed create
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/bitshares-pricefeed", line 7, in <module>
    from bitshares_pricefeed.cli import main
  File "/home/ubuntu/.local/lib/python3.5/site-packages/bitshares_pricefeed/cli.py", line 7, in <module>
    from bitshares.price import Price
  File "/home/ubuntu/.local/lib/python3.5/site-packages/bitshares/__init__.py", line 1, in <module>
    from .bitshares import BitShares
  File "/home/ubuntu/.local/lib/python3.5/site-packages/bitshares/bitshares.py", line 9, in <module>
    from bitsharesbase import transactions, operations
  File "/home/ubuntu/.local/lib/python3.5/site-packages/bitsharesbase/transactions.py", line 3, in <module>
    from .signedtransactions import Signed_Transaction
  File "/home/ubuntu/.local/lib/python3.5/site-packages/bitsharesbase/signedtransactions.py", line 2, in <module>
    from .operations import Operation
  File "/home/ubuntu/.local/lib/python3.5/site-packages/bitsharesbase/operations.py", line 10, in <module>
    from .objects import GrapheneObject, isArgsThisClass
  File "/home/ubuntu/.local/lib/python3.5/site-packages/bitsharesbase/objects.py", line 15, in <module>
    from graphenebase.objects import Operation as GPHOperation
ImportError: cannot import name 'Operation'
```

**Comment by xeroc** [comment]
I recommend you install using `pip3 install --user .` from within the repository.
Or you use `python3 setup.py install --user`

**Comment by wmbutler** [comment]
This fixed it and instructions were updated accordingly.
